const boxDrawerTemplate = () => {
    let html = ``;
    html += `<fieldset>`;
    html += `<label for='typeOfStyle'>`;
    html += `type of style:`;
    html += `<select name='typeOfStyle' id='typeOfStyle'>`;
    html += `<option value='random'>random</option>`;
    html += `<option value='full clone'>full clone</option>`;
    html += `<option value='full reflect'>full reflect</option>`;
    html += `<option value='full rotate'>full rotate</option>`;
    html += `<option value='half reflect'>half reflect</option>`;
    html += `</select>`;
    html += `</label>`;
    html += `<label for='boxCount'>`;
    html += `box count:`;
    html += `<input name='boxCount' type='number' value='10' />`;
    html += `</label>`;
    html += `<label class='colors' for='primaryColor'>`;
    html += `primary color:`;
    html += `<br />`;
    html += `<label for='primaryDefault'>default</label>`;
    html += `<input name='primaryToggle' type='radio' id='primaryDefault' value='default' checked />`;
    html += `<label for='primaryRandom'>random</label>`;
    html += `<input name='primaryToggle' type='radio' id='primaryRandom' value='random' />`;
    html += `<label for='primaryChoose'>choose</label>`;
    html += `<input name='primaryToggle' type='radio' id='primaryChoose' value='choose' />`;
    html += `<input id='primaryColor' name='primaryColor' type='color' value='rgb(0,0,0)' />`;
    html += `</label>`;
    html += `<label class='colors' for='secondaryColor'>`;
    html += `secondary color:`;
    html += `<br />`;
    html += `<label for='secondaryDefault'>default</label>`;
    html += `<input name='secondaryToggle' type='radio' id='secondaryDefault' value='default' checked />`;
    html += `<label for='secondaryRandom'>random</label>`;
    html += `<input name='secondaryToggle' type='radio' id='secondaryRandom' value='random' />`;
    html += `<label for='secondaryChoose'>choose</label>`;
    html += `<input name='secondaryToggle' type='radio' id='secondaryChoose' value='choose' />`;
    html += `<input name='secondaryColor' type='color' value='#8f1fff' />`;
    html += `</label>`;
    html += `<label class='colors' for='backgroundColor'>`;
    html += `background color:`;
    html += `<br />`;
    html += `<label for='backgroundDefault'>default</label>`;
    html += `<input name='backgroundToggle' type='radio' id='backgroundDefault' value='default' checked />`;
    html += `<label for='backgroundRandom'>random</label>`;
    html += `<input name='backgroundToggle' type='radio' id='backgroundRandom' value='random' />`;
    html += `<label for='backgroundChoose'>choose</label>`;
    html += `<input name='backgroundToggle' type='radio' id='backgroundChoose' value='choose' />`;
    html += `<input name='backgroundColor' type='color' value='#cfcfcf' />`;
    html += `</label>`;
    html += `</fieldset>`;

    return html;
};
export default boxDrawerTemplate;
