const boxDrawerTemplate = () => {
	let html = ``;

	html += `<div class='separatorContainer'>`;
	html += `<div class='separators'>`;
	html += `<p>Box Count:`;
	html += `<input id='boxCount' class='inputField' type="number" value=10 />`;
	html += `</p>`;
	html += `</div>`;
	html += `<div class='separators'>`;
	html += `<p>Primary Color:</p>`;
	html += `<div class="primaryColorContainer btnContainer">`;
	html += `<button id='defaultPrimaryColorBtn' class='btns active'>Default</button>`;
	html += `<button id='randomPrimaryColorBtn' class='btns'>Random</button>`;
	html += `<button id='choosePrimaryColorBtn' class='btns'>`;
	html += `Choose`;
	html += `<input id="choosePrimaryColor" type="color" value="#000000" />`;
	html += `</button>`;
	html += `</div>`;
	html += `</div>`;
	html += `<div class='separators'>`;
	html += `<p>Secondary Color:</p>`;
	html += `<div class="secondaryColorContainer btnContainer">`;
	html += `<button id='defaultSecondaryColorBtn' class='btns active'>Default Random</button>`;
	html += `<button id='chooseSecondaryColorBtn' class='btns'>`;
	html += `Choose`;
	html += `<input id="chooseSecondaryColor" type="color" value="#8C00FF" />`;
	html += `</button>`;
	html += `</div>`;
	html += `</div>`;
	html += `<div class='separators'>`;
	html += `<p>Background Color:</p>`;
	html += `<div class="backgroundColorContainer btnContainer">`;
	html += `<button id='defaultBackgroundColorBtn' class='btns active'>Default</button>`;
	html += `<button id='randomBackgroundColorBtn' class='btns'>Random</button>`;
	html += `<button id='chooseBackgroundColorBtn' class='btns'>`;
	html += `Choose`;
	html += `<input id="chooseBackgroundColor" type="color" value="#EEEEEE" />`;
	html += `</button>`;
	html += `</div>`;
	html += `</div>`;
	html += `</div>`;
	html += `<div class="styleContainer btnContainer">`;
	html += `<button id='randomBtn' class='btns'>Random</button>`;
	html += `<button id='fullCloneBtn' class='btns'>Full Clone</button>`;
	html += `<button id='fullReflectBtn' class='btns'>Full Reflect</button>`;
	html += `<button id='fullRotateBtn' class='btns'>Full Rotate</button>`;
	html += `<button id='halfReflectBtn' class='btns'>Full Reflect</button>`;
	html += `</div>`;

	return html;
};
export default boxDrawerTemplate;
